# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://jamestek.net"
languageCode = "en-AU"
title = "My Awesome Title"

# Metadata
[params]
  author = "Your name"
  description = "Cool description"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "https://images.wallpaperscraft.com/image/blue_light_line_65813_2560x1440.jpg"
  title = "Web Development & Marketing for individuals and small businesses"
  description = "To make a big impression"

# Navigation section
[params.nav]
  mission = "Mission"
  services = "Services"
  team = "People"
  contact = "Contact"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "Like water, our solutions are powerful and adaptable. Bruce Lee would be proud."
    description = "<p>Our custom-made services provide an impressive platform at an easy price. </p><ul class='checked'><li>Static web pages</li><li>Custom resumes</li><li>Social media consultation</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Resources"
    subtitle = "Each managed webpage is all-inclusive."
    description = "<p>We provide everything you need to have fully-functioning static and landing pages.</p><ul class='checked'><li>Free AWS S3 storage</li><li>Private Github repository management</li><li>Site hosting</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Strategy"
    subtitle = "Minimal style combined with focused content deliver an unrivaled image."
    description = "<p>Our design process makes it easy to find your brand. We ask a few questions to get started, then tailor everything to your desire.</p><ul class='checked'><li>Google Material Design</li><li>Brand voice consultation</li><li>Basic image editing</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = true
  video = true
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Services"
  description = "Here's what we can do for you."

  [[params.services.item]]
    icon = "icon-present"
    title = "Web Development & Maintenance"
    description = "Save time and effort by letting us make and maintain your website. We use services with enhanced control; Wordpress just won't cut it."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Custom Resumes"
    description = "Trying to get that new job? We can help with custom-designed resumes, created by knowledgable hiring managers."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Brand Voice Consultation"
    description = "Is your brand spicy like the famous Wendys Twitter? Or is it elegant like Porsche? Either way, we help you find your voice."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "The right words are the ones that efficiently express yourself or your brand. Our copywriters are those college nerds who love to write."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Search Engine Optimization"
    description = "H1 vs H2. Alt text and internal linking. We know how to get your brand higher in the search rankings."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "We'll fix anything that breaks, and change whatever you want. After all, you're the one paying."

# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "Inspired Space"
    subtitle = "Web Design, Brand Consultation"
    img = "https://imgur.com/a/qullaVE"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Alice Doe"
    position = "Chief overlord"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person2.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "John Doe"
    position = "Chief haranguer"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person3.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "#"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"
  